### ISSUE TITLE
CI link is a reroute to spam

### ISSUE THREAD

**Issue by Brrrknee** [gifnksm/ProjectEulerRust#12]
@gifnksm gifnksm/ProjectEulerRust has a reference to a "viable" site "rust-CI.org" which is nothing more than a spam redirect to a wild array of marketing push websites. garbage!  even typing the link into a browser has it immediately hijacked/ rerouted to a chain of nefarious sites that end up with any of many marketing scam sites as the final page.  
I would hope and trust that was not your intention.

**Comment by gifnksm** [comment]
Thank you for reporting. I didn't intend to navigate to spam website (`rust-ci.org` was a useful website... I'm very sad about the domain owned by a spammer...)

I'll remove the link soon.
